[cerebrium.deployment]
name = "mtailor-mlops-assignment"
python_version = "3.10"
include = ["./*", "main.py", "cerebrium.toml"]
exclude = [".*"]
shell_commands = [""]

[cerebrium.hardware]
cpu = 2.0
memory = 4.0
compute = "TURING_T4"
gpu_count = 1
provider = "aws"
region = "us-east-1"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/health"
dockerfile_path = "../Dockerfile"

[cerebrium.scaling]
min_replicas = 1
max_replicas = 1
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

