name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -t image-classification:test .
    
    - name: Test Docker image
      run: |
        docker run --rm image-classification:test python3 -c "import onnxruntime; print('ONNX Runtime version:', onnxruntime.__version__)"
        docker run --rm image-classification:test python3 -c "import uvicorn; print('Uvicorn version:', uvicorn.__version__)"